// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TombolaGame.Data;

#nullable disable

namespace TombolaGame.Migrations
{
    [DbContext(typeof(TombolaContext))]
    [Migration("20250819185011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TombolaGame.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TombolaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TombolaId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("TombolaGame.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TombolaId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TombolaId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TombolaGame.Models.Tombola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tombolas");
                });

            modelBuilder.Entity("TombolaGame.Models.Award", b =>
                {
                    b.HasOne("TombolaGame.Models.Tombola", "Tombola")
                        .WithMany("Awards")
                        .HasForeignKey("TombolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tombola");
                });

            modelBuilder.Entity("TombolaGame.Models.Player", b =>
                {
                    b.HasOne("TombolaGame.Models.Tombola", null)
                        .WithMany("Players")
                        .HasForeignKey("TombolaId");
                });

            modelBuilder.Entity("TombolaGame.Models.Tombola", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
