// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TombolaGame.Data;

#nullable disable

namespace TombolaGame.Migrations
{
    [DbContext(typeof(TombolaContext))]
    partial class TombolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerTombola", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("integer");

                    b.Property<int>("TombolasId")
                        .HasColumnType("integer");

                    b.HasKey("PlayersId", "TombolasId");

                    b.HasIndex("TombolasId");

                    b.ToTable("PlayerTombola");
                });

            modelBuilder.Entity("TombolaGame.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TombolaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TombolaId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("TombolaGame.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TombolaGame.Models.Tombola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaximumAwards")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumAwards")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("StrategyType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tombolas");
                });

            modelBuilder.Entity("TombolaGame.Models.TombolaWinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TombolaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TombolaId");

                    b.ToTable("TombolaWinner");
                });

            modelBuilder.Entity("PlayerTombola", b =>
                {
                    b.HasOne("TombolaGame.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TombolaGame.Models.Tombola", null)
                        .WithMany()
                        .HasForeignKey("TombolasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TombolaGame.Models.Award", b =>
                {
                    b.HasOne("TombolaGame.Models.Tombola", "Tombola")
                        .WithMany("Awards")
                        .HasForeignKey("TombolaId");

                    b.Navigation("Tombola");
                });

            modelBuilder.Entity("TombolaGame.Models.TombolaWinner", b =>
                {
                    b.HasOne("TombolaGame.Models.Award", "Award")
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TombolaGame.Models.Player", "Player")
                        .WithMany("TombolaWins")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TombolaGame.Models.Tombola", "Tombola")
                        .WithMany("Winners")
                        .HasForeignKey("TombolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Player");

                    b.Navigation("Tombola");
                });

            modelBuilder.Entity("TombolaGame.Models.Player", b =>
                {
                    b.Navigation("TombolaWins");
                });

            modelBuilder.Entity("TombolaGame.Models.Tombola", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
